---
- hosts: windows_servers
  vars:
    source_file: "/tmp/text.txt"
  
  tasks:
  - name: Copy a test file to all windows server
    win_copy :
      src: "{{source_file}}"
      dest: "c:\\Windows\\Temp\\text.txt"